ProjectPRJ1/src/java/model/Music.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author ACER
 */
public class Music {

    private int MusicID;
    private String Name;
    private String Link;
    private Composer ComposerID;
    private User UploaderID;
    private String Desc;
    private String Artwork;
    private String Genre;
    private double AvgMark;
    private String StrMark;

    public Music(int MusicID, String Name, String Link, Composer ComposerID, User UploaderID, String Desc, String Artwork, String Genre, double AvgMark) {
        this.MusicID = MusicID;
        this.Name = Name;
        this.Link = Link;
        this.ComposerID = ComposerID;
        this.UploaderID = UploaderID;
        this.Desc = Desc;
        this.Artwork = Artwork;
        this.Genre = Genre;
        this.AvgMark = AvgMark;
    }

    public Music() {
    }

    public Music(int MusicID, String Name, String Link, Composer ComposerID, User UploaderID, String Desc, String Artwork, String Genre) {
        this.MusicID = MusicID;
        this.Name = Name;
        this.Link = Link;
        this.ComposerID = ComposerID;
        this.UploaderID = UploaderID;
        this.Desc = Desc;
        this.Artwork = Artwork;
        this.Genre = Genre;
    }

    public Music(int MusicID, String Name, String Link, Composer ComposerID, User UploaderID, String Desc, String Artwork, String Genre, String StrMark) {
        this.MusicID = MusicID;
        this.Name = Name;
        this.Link = Link;
        this.ComposerID = ComposerID;
        this.UploaderID = UploaderID;
        this.Desc = Desc;
        this.Artwork = Artwork;
        this.Genre = Genre;
        this.StrMark = StrMark;
    }

    public String getStrMark() {
        return StrMark;
    }

    public void setStrMark(String StrMark) {
        this.StrMark = StrMark;
    }

    public double getAvgMark() {
        return AvgMark;
    }

    public void setAvgMark(double AvgMark) {
        this.AvgMark = AvgMark;
    }

    public int getMusicID() {
        return MusicID;
    }

    public void setMusicID(int MusicID) {
        this.MusicID = MusicID;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getLink() {
        return Link;
    }

    public void setLink(String Link) {
        this.Link = Link;
    }

    public Composer getComposerID() {
        return ComposerID;
    }

    public void setComposerID(Composer ComposerID) {
        this.ComposerID = ComposerID;
    }

    public User getUploaderID() {
        return UploaderID;
    }

    public void setUploaderID(User UploaderID) {
        this.UploaderID = UploaderID;
    }

    public String getDesc() {
        return Desc;
    }

    public void setDesc(String Desc) {
        this.Desc = Desc;
    }

    public String getArtwork() {
        return Artwork;
    }

    public void setArtwork(String Artwork) {
        this.Artwork = Artwork;
    }

    public String getGenre() {
        return Genre;
    }

    public void setGenre(String Genre) {
        this.Genre = Genre;
    }

    @Override
    public String toString() {
        return "Music{" + "MusicID=" + MusicID + ", Name=" + Name + ", Link=" + Link + ", ComposerID=" + ComposerID + ", UploaderID=" + UploaderID + ", Desc=" + Desc + ", Artwork=" + Artwork + ", Genre=" + Genre + '}';
    }

}

ProjectPRJ1/src/java/model/Reply.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Date;
import java.sql.Timestamp;

/**
 *
 * @author ACER
 */
public class Reply {
    private int ReplyID;
    private User username;
    private Timestamp Time;
    private String Content;

    public Reply() {
    }

    public Reply(int ReplyID, User username, Timestamp Time, String Content) {
        this.ReplyID = ReplyID;
        this.username = username;
        this.Time = Time;
        this.Content = Content;
    }

    public int getReplyID() {
        return ReplyID;
    }

    public void setReplyID(int ReplyID) {
        this.ReplyID = ReplyID;
    }

    public User getUsername() {
        return username;
    }

    public void setUsername(User username) {
        this.username = username;
    }

    public Timestamp getTime() {
        return Time;
    }

    public void setTime(Timestamp Time) {
        this.Time = Time;
    }

    public String getContent() {
        return Content;
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    @Override
    public String toString() {
        return "Reply{" + "ReplyID=" + ReplyID + ", username=" + username + ", Time=" + Time + ", Content=" + Content + '}';
    }
    
    
    
}

ProjectPRJ1/src/java/model/Review.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

/**
 *
 * @author ACER
 */
public class Review {

    private int ReviewID;
    private String Content;
    private User reviewerID;
    private double Mark;

    public Review() {
    }

    public Review(int ReviewID, String Content, User reviewerID, double Mark) {
        this.ReviewID = ReviewID;
        this.Content = Content;
        this.reviewerID = reviewerID;
        this.Mark = Mark;
    }

    public int getReviewID() {
        return ReviewID;
    }

    public void setReviewID(int ReviewID) {
        this.ReviewID = ReviewID;
    }

    public String getContent() {
        return Content;
    }

    public void setContent(String Content) {
        this.Content = Content;
    }

    public User getReviewerID() {
        return reviewerID;
    }

    public void setReviewerID(User reviewerID) {
        this.reviewerID = reviewerID;
    }

    public double getMark() {
        return Mark;
    }

    public void setMark(double Mark) {
        this.Mark = Mark;
    }

    @Override
    public String toString() {
        return "Review{" + "ReviewID=" + ReviewID + ", Content=" + Content + ", reviewerID=" + reviewerID + ", Mark=" + Mark + '}';
    }

}

ProjectPRJ1/src/java/model/Thread.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Date;

/**
 *
 * @author ACER
 */
public class Thread {

    private int ThreadID;
    private String ThreadName;
    private User CreatorID;
    private Date createdDate;
    private int TotalReplies;

    public Thread() {
    }

    public Thread(int ThreadID, String ThreadName, User CreatorID, Date createdDate) {
        this.ThreadID = ThreadID;
        this.ThreadName = ThreadName;
        this.CreatorID = CreatorID;
        this.createdDate = createdDate;
    }

    public Thread(int ThreadID, String ThreadName, User CreatorID, Date createdDate, int TotalReplies) {
        this.ThreadID = ThreadID;
        this.ThreadName = ThreadName;
        this.CreatorID = CreatorID;
        this.createdDate = createdDate;
        this.TotalReplies = TotalReplies;
    }

    public int getTotalReplies() {
        return TotalReplies;
    }

    public void setTotalReplies(int TotalReplies) {
        this.TotalReplies = TotalReplies;
    }

    public int getThreadID() {
        return ThreadID;
    }

    public void setThreadID(int ThreadID) {
        this.ThreadID = ThreadID;
    }

    public String getThreadName() {
        return ThreadName;
    }

    public void setThreadName(String ThreadName) {
        this.ThreadName = ThreadName;
    }

    public User getCreatorID() {
        return CreatorID;
    }

    public void setCreatorID(User CreatorID) {
        this.CreatorID = CreatorID;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    @Override
    public String toString() {
        return "Thread{" + "ThreadID=" + ThreadID + ", ThreadName=" + ThreadName + ", CreatorID=" + CreatorID + ", createdDate=" + createdDate + '}';
    }

}

ProjectPRJ1/src/java/controller/ArtistListServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */

package controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.util.List;
import model.Composer;

/**
 *
 * @author ACER
 */
@WebServlet(name="ArtistListServlet", urlPatterns={"/artistList"})
public class ArtistListServlet extends HttpServlet {
   
    /** 
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code> methods.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ArtistListServlet</title>");  
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ArtistListServlet at " + request.getContextPath () + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    } 

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /** 
     * Handles the HTTP <code>GET</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        DAO d = new DAO();
        List<Composer> list = d.getAllComposers();
        request.setAttribute("data", list);
        request.getRequestDispatcher("ArtistList.jsp").forward(request, response);
    } 

    /** 
     * Handles the HTTP <code>POST</code> method.
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
    throws ServletException, IOException {
        processRequest(request, response);
    }

    /** 
     * Returns a short description of the servlet.
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

ProjectPRJ1/src/java/controller/ReviewListServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller;

import dal.DAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import model.Music;

/**
 *
 * @author ACER
 */
@WebServlet(name = "ReviewListServlet", urlPatterns = {"/review"})
public class ReviewListServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet ReviewListServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet ReviewListServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String sortid_raw = request.getParameter("sortid");
        try {
            int sortid = Integer.parseInt(sortid_raw);
            DAO d = new DAO();
            List<Music> list = d.getAllMusic();
            
            if (sortid == 1) {
                list = d.getAllMusic();
            }
            else if(sortid==2){
                list = d.getMusicOrderedByMark();
            }
            else if(sortid==3){
                list = d.getMusicOrderedByLowMark();
            }
            else if(sortid==4){
                list = d.getMusicOrderedByName();
            }
                    
            List<Music> list2 = new ArrayList<>();
            for (Music m : list) {
                m = new Music(m.getMusicID(), m.getName(), m.getLink(), m.getComposerID(), m.getUploaderID(), m.getDesc(), m.getArtwork(), m.getGenre(), "");
                m.setStrMark(d.getMarkStrByMusicID(m.getMusicID()));
                list2.add(m);
            }

            request.setAttribute("data", list2);
            request.getRequestDispatcher("ReviewList.jsp").forward(request, response);
        } catch (NumberFormatException e) {
            System.out.println(e.getMessage());
        }

    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

ProjectPRJ1/web/reviewDetail.jsp
<%-- 
    Document   : reviewDetail
    Created on : Jul 11, 2022, 1:52:51 AM
    Author     : ACER
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        <link rel="stylesheet" href="CSS/header.css">
        <link rel="stylesheet" href="CSS/reviewdetail.css">
        <!--Inter font-->
        <link href='https://fonts.googleapis.com/css?family=Inter' rel='stylesheet'>
        <link rel="stylesheet" href="CSS/star.css">
        <style>
            body {
                font-family: 'Inter';
                font-size: 22px;
            }
        </style>
    </head>
    <body>
        <div class="container-md">
            <div class="banner">
                <div class="row">
                    <!--logo-->
                    <div class="col-md-1"><img src="images/music-logo-png-2350.png" alt="alt"/></div>
                    <!--search bar-->
                    <div class="col-md-4" id="searchBar">
                        <div class="input-group">
                            <form action="search" id="searchs">
                                <input type="search" class="form-control rounded searchType" placeholder="Search for forum...." aria-label="Search" aria-describedby="search-addon" name="threadName"/>
                                <!--                            <button type="button" class="btn btn-outline-primary">Search</button>-->
                                <input type="hidden" name="CreatorID" value=""/>
                                <input type="hidden" name="fromDate" value=""/>
                                <input type="hidden" name="toDate" value=""/>
                                <input type="hidden" name="sid" value="1"/>
                                <input type="submit" class="btn btn-outline-primary" value="Search">
                            </form>
                        </div>
                    </div>
                    <!--home-->
                    <div class="col-md-1 redir">
                        <a href="home">Home</a>
                    </div>
                    <!--Forum-->
                    <div class="col-md-1 redir">
                        <a href="threadList">Forum</a>
                    </div>
                    <!--Review-->
                    <div class="col-md-1 redir">
                        <a href="review?sortid=1">Review</a>
                    </div>
                    <div class="col-md-1 redir">
                        <a href="artistList">Artists</a>
                    </div>
                </div>
            </div>
        </div>

        <br/>

        

        <div class="container-md">
            <div class="row">
                <div class="col-sm-12 col-xs-12 col-md-4 artwork">
                    <img src="${requestScope.song.artwork}" alt="alt"/>
                    <br/>
                    <div class="avgMark">
                        <span>${requestScope.mark}</span>
                        <span><i class="fa-solid fa-star"></i></span>
                    </div>
                </div>
                <div class="col-sm-12 col-xs-12 col-md-8 detail">
                    <div class="row">
                        <div class="col-sm-12 col-xs-12 col-md-7">
                            <h2 class="songName">${requestScope.song.name}</h2>
                        </div>
                        <div class="col-sm-12 col-xs-12 col-md-4 uploader">
                            <h3>Uploaded by: ${requestScope.song.uploaderID.username}</h3>
                        </div>
                        <c:if test="${sessionScope.account.username == requestScope.song.uploaderID.username}">
                            <div class="col-sm-12 col-xs-12 col-md-1 edit">
                                <a href="updateSong?mid=${requestScope.song.musicID}">[Edit]</a>
                            </div>
                        </c:if>
                    </div>
                    <hr>

                    <h3 class="composerName">Artist: ${requestScope.song.composerID.composerName}</h3>
                    <h3 class="genre">Genre: ${requestScope.song.genre}</h3>
                    <h3 class="description">Description</h3>
                    <p class="desc">${requestScope.song.desc}</p>
                    <div class="playButton"><a target=”_blank” href="${requestScope.song.link}">Play</a></div>
                </div>
            </div>
        </div>

        <hr>
        <div class="container-md">
            <div class="row">
                <div class="AOR">${requestScope.aor} Reviews</div>
                <c:forEach items="${requestScope.data}" var="r">
                    <c:if test="${r.reviewID == requestScope.ruid && r.reviewerID.username == sessionScope.account.username}">
                        <div>
                            <h3>
                                Edit your review: 
                            </h3>
                            <span class="usernameRV">${sessionScope.account.username}</span>
                        </div>
                        <form action="updateReview" method="post">
                            <!--                    <input type="text" class="form-control rvContentAdd" aria-label="Small" aria-describedby="inputGroup-sizing-sm" name="content" autocomplete="off">-->
                            <textarea name="reviewContent" class="descBox">${r.content}</textarea>
                            <div class="rating-wrap">
                                <div class="center">
                                    <fieldset class="rating">
                                        <input type="radio" id="star5" name="rating" value="5"/><label for="star5" class="full" title="Awesome"></label>
                                        <input type="radio" id="star4.5" name="rating" value="4.5"/><label for="star4.5" class="half"></label>
                                        <input type="radio" id="star4" name="rating" value="4"/><label for="star4" class="full"></label>
                                        <input type="radio" id="star3.5" name="rating" value="3.5"/><label for="star3.5" class="half"></label>
                                        <input type="radio" id="star3" name="rating" value="3"/><label for="star3" class="full"></label>
                                        <input type="radio" id="star2.5" name="rating" value="2.5"/><label for="star2.5" class="half"></label>
                                        <input type="radio" id="star2" name="rating" value="2"/><label for="star2" class="full"></label>
                                        <input type="radio" id="star1.5" name="rating" value="1.5"/><label for="star1.5" class="half"></label>
                                        <input type="radio" id="star1" name="rating" value="1"/><label for="star1" class="full"></label>
                                        <input type="radio" id="star0.5" name="rating" value="0.5"/><label for="star0.5" class="half"></label>
                                    </fieldset>
                                </div>

                                <h4 id="rating-value"></h4>
                            </div>

                            <input type="hidden" name="username" value="${r.reviewerID.username}"/>
                            <input type="hidden" name="rid" value="${r.reviewID}"/>
                            <input type="hidden" name="mid" value="${requestScope.song.musicID}"/>

                            <button type="submit" class="editbtn btn btn-dark">Edit</button>
                        </form>
                    </c:if>
                    <c:if test="${r.reviewID == requestScope.ruid && r.reviewerID.username != sessionScope.account.username}">
                        <h3>You need to login to edit your comment</h3>
                    </c:if>
                    <c:if test="${r.reviewID != requestScope.ruid}">
                        <div class="reviewWrap">
                            <div class="reviewHeader">
                                <div class="row">
                                    <div class="col-6">
                                        <span class="reviewerUser">${r.reviewerID.username}</span>
                                        <span>rated this song </span>
                                        <span class="Mark">${r.mark}</span>
                                        <span><i class="fa-solid fa-star"></i></span>
                                    </div>
                                    <div class="col-6 editRv">
                                        <c:if test="${r.reviewerID.username == sessionScope.account.username && requestScope.ruid == 0}">
                                            <a class="updateBtn" href="reviewDetail?mid=${requestScope.song.musicID}&ruid=${r.reviewID}">Update this review</a>
                                            <a class="deleteRvBtn" href="deleteReview?rid=${r.reviewID}&mid=${requestScope.song.musicID}">Delete this review</a>
                                        </c:if>
                                    </div>
                                </div>
                            </div>
                            <p class="rvContent">${r.content}</p>
                        </div>
                        <br/>
                    </c:if>
                </c:forEach>
            </div>
            <c:if test="${sessionScope.account == null && ruid == 0}">
                <h3>You need to login to add your review</h3>
            </c:if>
            <c:if test="${sessionScope.account != null && ruid == 0}">
                <span>Add your review here</span>
                <span class="usernameRV">${sessionScope.account.username}</span>
                <form action="addReview" method="post">
                    <!--                    <input type="text" class="form-control rvContentAdd" aria-label="Small" aria-describedby="inputGroup-sizing-sm" name="content" autocomplete="off">-->
                    <textarea name="reviewContent" class="descBox"></textarea>
                    <div class="rating-wrap">
                        <div class="center">
                            <fieldset class="rating">
                                <input type="radio" id="star5" name="rating" value="5"/><label for="star5" class="full" title="Awesome"></label>
                                <input type="radio" id="star4.5" name="rating" value="4.5"/><label for="star4.5" class="half"></label>
                                <input type="radio" id="star4" name="rating" value="4"/><label for="star4" class="full"></label>
                                <input type="radio" id="star3.5" name="rating" value="3.5"/><label for="star3.5" class="half"></label>
                                <input type="radio" id="star3" name="rating" value="3"/><label for="star3" class="full"></label>
                                <input type="radio" id="star2.5" name="rating" value="2.5"/><label for="star2.5" class="half"></label>
                                <input type="radio" id="star2" name="rating" value="2"/><label for="star2" class="full"></label>
                                <input type="radio" id="star1.5" name="rating" value="1.5"/><label for="star1.5" class="half"></label>
                                <input type="radio" id="star1" name="rating" value="1"/><label for="star1" class="full"></label>
                                <input type="radio" id="star0.5" name="rating" value="0.5"/><label for="star0.5" class="half"></label>
                            </fieldset>
                        </div>

                        <h4 id="rating-value"></h4>
                    </div>

                    <input type="hidden" name="username" value="${sessionScope.account.username}"/>
                    <input type="hidden" name="mid" value="${requestScope.song.musicID}"/>
                    <button type="submit" class="submitbtn btn btn-dark">Submit</button>
                </form>
            </c:if>
        </div>
        <script src="Javascript/star-ratings.js"></script>
    </body>
</html>

ProjectPRJ1/web/testStar.jsp
<%-- 
    Document   : testStar
    Created on : Jul 11, 2022, 7:30:34 PM
    Author     : ACER
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Star rating</title>
        <link rel="stylesheet" href="CSS/star.css">
    </head>
    <body>
        <div class="container">
            <div class="rating-wrap">
                <div class="center">
                    <fieldset class="rating">
                        <input type="radio" id="star5" name="rating" value="5"/><label for="star5" class="full" title="Awesome"></label>
                        <input type="radio" id="star4.5" name="rating" value="4.5"/><label for="star4.5" class="half"></label>
                        <input type="radio" id="star4" name="rating" value="4"/><label for="star4" class="full"></label>
                        <input type="radio" id="star3.5" name="rating" value="3.5"/><label for="star3.5" class="half"></label>
                        <input type="radio" id="star3" name="rating" value="3"/><label for="star3" class="full"></label>
                        <input type="radio" id="star2.5" name="rating" value="2.5"/><label for="star2.5" class="half"></label>
                        <input type="radio" id="star2" name="rating" value="2"/><label for="star2" class="full"></label>
                        <input type="radio" id="star1.5" name="rating" value="1.5"/><label for="star1.5" class="half"></label>
                        <input type="radio" id="star1" name="rating" value="1"/><label for="star1" class="full"></label>
                        <input type="radio" id="star0.5" name="rating" value="0.5"/><label for="star0.5" class="half"></label>
                    </fieldset>
                </div>

                <h4 id="rating-value"></h4>
            </div>
        </div>

        <script src="Javascript/star-ratings.js"></script>
    </body>
</html>